### ISSUE TITLE
1.12.0

### ISSUE THREAD

**Issue by Leon1324765s** [ona-li-toki-e-jan-Epiphany-tawa-mi/Survival-Command-Blocks#4]
Is it impossible for the mod to be made in the version 1.20.0?

**Comment by ona-li-toki-e-jan-Epiphany-tawa-mi** [comment]
https://github.com/ona-li-toki-e-jan-Epiphany-tawa-mi/Survival-Command-Blocks/releases/tag/RELEASE-1.20.0-V0.1.4

Untested but should work fine.
